### ISSUE TITLE
[VSLCV] bar chart

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1144]
**Package** lib-classifier

**Feature or Issue Description**
Issue tracking the bar chart portion of the variable star light curve viewer.

https://projects.invisionapp.com/d/main?origin=v7?origin=v7#/projects/prototypes/17294981

**To Dos**

- [x] 2D axes (#1056)
  - [x] Label per axis (#1056)
- [x] Display label per bar (#1056)
- [x] Individual color styling per bar (#1056)
- [x] Responsive (#1056)
- [x] Functional in light and dark theme (#1056)

**Comment by srallen** [comment]
Additional enhancements:

- [ ] accessible bars
- [ ] grouped bar chart
