### ISSUE TITLE
Design feedback: Project Home Page

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/front-end-monorepo#1152]
- [x] When a project does not have an active workflow, show a [disabled button](https://projects.invisionapp.com/d/main#/projects/prototypes/12923997/assets/77727637) rather than nothing (#1150)

- [x] All buttons need hover states (#1188, #1204)

- [x] Add spacing between multiple workflow buttons (#1170)

- [x] Hero component always min-height 545px. Classify + buttons should align to the bottom, while the title and description should align to the top. (#1171)

- [x] Recent subjects 270x200, crop images from the center at the longest side. This is how the current Recents widget handles images, and should be continued: For both consistency across projects and in consideration of smaller screen sizes. 

- [x] Dark theme toggle feels awkward. Can all the module boxes line up with the right side of the Recents module, so there's a consistent edge on the right side, even if it's different to the edge on the left side, see [The Atlantic](https://www.theatlantic.com/entertainment/archive/2019/09/blink-182-nine-album-review-wistful-and-catchy/598420/) for a cool iteration of this. (#1186)

- [x] What did we decide about the progress bars on the individual workflow buttons? https://zooniverse.slack.com/archives/C0Z7YNTSL/p1554151344033200 Is I think where we landed? Should still figure out something for times when a hover isn't possible. Happy to talk about this more. (#1151, #1204)

***Small Screens / mobile***

- [x] Hero component should always be 230px tall. The PH: TESS project is very tall and on some browsers and devices only the image will appear before scrolling. (#1155)

- [x] Recents – move pagination dots to underneath subject image; they are not currently visible on top of the image.

**Comment by eatyourgreens** [comment]
Recents are using a [Grommet Carousel](https://v2.grommet.io/carousel) on small screens, which made them easy to set up but doesn't give us much control over how the controls are displayed. I have the pagination turned off in the code, but that option isn't supported by the version of Grommet that we're using.

**Comment by srallen** [comment]
Grommet version just needs to be bumped to disable the pagination on small screens.

**Comment by beckyrother** [comment]
If the pagination is disabled will it be clear that it's a carousel?

**Comment by srallen** [comment]
@beckyrother it's now visible on https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/

The arrow buttons are still available with the Grommet carousel on small screen sizes, though we need to adjust the color of the icons on the light theme version (they're too dark gray, should probably be white with an opacity underneath?):

<img width="374" alt="Screen Shot 2019-09-23 at 10 32 50 AM" src="https://user-images.githubusercontent.com/5016731/65440084-ceeae900-dded-11e9-811a-d5abdad9724c.png">

Dark theme:
<img width="375" alt="Screen Shot 2019-09-23 at 10 32 56 AM" src="https://user-images.githubusercontent.com/5016731/65440025-b8dd2880-dded-11e9-9897-e07eb408fe19.png">

**Comment by beckyrother** [comment]
Agreed, probably both light and dark should have a semitransparent background just to account for any type of image – white for the light theme and #000 black for the dark theme. Thanks!

**Comment by eatyourgreens** [comment]
#1153 fixes the Talk thumbnails.

**Comment by eatyourgreens** [comment]
#1160 fixes the subject thumbnails for video projects, but I wasn't sure if that's a priority for the next milestone.

**Comment by eatyourgreens** [comment]
>All buttons need hover states

@beckyrother what are the missing hover states? I'm looking at the invision designs for the project home page but I'm not sure what I should be looking at.

**Comment by eatyourgreens** [comment]
The call to action is off the bottom of the screen for me in Chrome and Firefox (13-inch MacBook with a Retina display.)
![Screenshot of the PH-TESS home page showing that the Classify button is hidden off the bottom of the screen.](https://user-images.githubusercontent.com/59547/65891729-f23d0780-e39c-11e9-8fc3-8a4c8f43feea.png)

**Comment by beckyrother** [comment]
> @beckyrother what are the missing hover states? I'm looking at the invision designs for the project home page but I'm not sure what I should be looking at.

@eatyourgreens they should be the same as on the classify interface. Here's a style sheet: https://projects.invisionapp.com/d/main#/projects/prototypes/12923997/assets/77727637?folderID=28561320

**Comment by eatyourgreens** [comment]
Great. I should be able to copy them over from the classifier.

**Comment by srallen** [comment]
If we're sharing code and styles between libraries and apps, let's put them in the react components library?

**Comment by beckyrother** [comment]
Button styles and most text styles have been copied over from the classifier onto this page and will be reused in subsequent new pages, so they shouldn't need to be recreated.

**Comment by srallen** [comment]
Yeah, we should update the theme when appropriate and/or add base components to the shared components library.

**Comment by rogerhutchings** [comment]
Also, we have #1248 and #887 for writing button states, so I'm going to close this for now for the sake of shipping the homepage.
