### ISSUE TITLE
Review survey task accessibility, focus, and key controls

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#1991]
After #1990, survey task selections made (choice, filter, question, etc.) will persist and function as expected, at which point it will be important to re-review accessibility, focus, and key controls throughout the UX of the survey task.

This issue can be used to note specifics identified in other related issues or PRs, or however helpful.

ToDos:
- [x] radio input can be unselected/cleared (#2194)
- [x] clicking Not This in Choice deletes choice from annotation (#2247)
- [x] Choice Question inputs focus (#2250)
- [x] refactor Choices as [grid columns](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout#auto-placement_by_column) or other way to improve accessibility, [related comment](https://github.com/zooniverse/front-end-monorepo/pull/1979#pullrequestreview-572530164) (#2256) 
- [x] Choices onKeyDown similar to PFE (#2256) 
- [x] refactor StyledHorizontalRule to border on FilterStatus (#2265)
- [x] ChoiceButton custom theme, [related comment](https://github.com/zooniverse/front-end-monorepo/pull/1979#discussion_r561327574) (#2265)
- [x] Choice dark theme styling (#2265)
- [x] radio input clear on keydown (PFE = space or backspace) (#2305)
- [x] with disable prop, disable Choices and FilterStatus (#2308)

**Comment by mcbouslog** [comment]
Great suggestion from @eatyourgreens - make list of choices an HTML list for improved accessibility and navigatablity

**Comment by eatyourgreens** [comment]
If we keep the list of choices as a grouped control, which it is in PFE, then it should probably have a menu role, with each choice wrapped in a menuItem. I forgot that in the original code.

**Comment by eatyourgreens** [comment]
The list of choices should also be a single list, styled into grid columns, not three lists.
