### ISSUE TITLE
TextFromSubject post-beta updates

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#3663]
## FEM - DigiLeap

Task/UI feedback

- [ ] Can't get the Announcements banner back after 'X'-ing out (lost access to beta form link bc of this) #4635 
- [x] Can we make the initial text box bigger? #4634 
- [ ] "In this project, if I click Done & Talk to see if anyone has made a comment and then go back to classifying mode by using the Back arrow button at the top of my screen, the system shows me the subject I have just classified with a red banner above the top saying "You've already seen this subject" and then I have to refresh the subject again." ([See Talk thread](https://www.zooniverse.org/projects/md68135/notes-from-nature-labs/talk/2629/2598999?comment=4253737))
- [x] Can the font in the pre-populated text area be a programming font, instead of Karla? Currently it's hard to distinguish between `0` and `O` or `l` and `I` and being able to identify those substitutions is crucial for the OCR training process. Rafe has recommended the fonts "Source Sans Pro" and "Ubuntu" for this. see #4195 
- [ ] In dark mode, 'Reset' grey text is a bit hard to see against the darker grey background. see #4413 
- [ ] change Reset button color to yellow (like the Announcement banner?) so people aren't tempted to accidentally click? Not super common, but the color might have an impact.

Documentation
- [ ] Be sure to include guidance around line breaks (e.g. to include line breaks on the classify page, your subject data must include X)

**Comment by eatyourgreens** [comment]
The ‘are you sure you want to leave’ popup shows for all subjects, even if you haven’t started a classification.
