### ISSUE TITLE
Missing ADRs

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#4214]
A few changes are missing decision records. 

- [x] Static builds for project pages (#5863.) 
- [x] Adding the Panoptes translations API to the NextJS app and the classifier library (#5832.)
- [x] Building the libraries as straight Babel transforms, without Webpack (#5827.)

**Comment by goplayoutside3** [comment]
Since this Issue is now a year old, I'm not sure ADRs on these subjects would be helpful. Static builds for the project pages is well documented in Next.js's docs. 

@eatyourgreens I think you're most familiar with the second two points, and while there's no obligation to follow-up with ADR's, I'd like to know if I can close this Issue or if you plan to write them.

**Comment by eatyourgreens** [comment]
> Static builds for the project pages is well documented in Next.js's docs.

The Next.js docs won't tell you why Zooniverse switched from dynamic builds to static builds:
- why dynamic builds were a problem for Zooniverse projects. 
- how static builds solved those problems. 
- what compromises were involved in that decision. 

An ADR captures the context of a decision, so that it isn't lost. 

These ADRs still seem helpful, based on questions I've been getting already about things that I've worked on. I might return to them, but I'm volunteering my unpaid time here so can't commit to anything definite.
