### ISSUE TITLE
Design: please fix before beta launch

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/front-end-monorepo#695]
### Tutorial / all modals
- [x] Pagination dots are too far apart, arrows are even farther. There should be 5px between each element
- [x] Between the teal bar and the top of the H2 should just be 30px. 
- [x] Why does 'Planet Finders BETA Tutorial' appear on each slide
- [x] The entire contents of the tutorial should scroll, not just the text part
- [ ] Modal text (need help, add to collections, etc) remains underlined after the modal has been closed

### Classify interface
- [x] 5px padding between 'info' etc icon and label (in #617)
- [x] 5px padding between these buttons and the bottom of the subject image: (in #617)
![Classifier_2018_Preview_Mode_-_InVision](https://user-images.githubusercontent.com/1392130/55896718-88c60400-5b84-11e9-9337-6a062577e83f.png)
- [x] Padding within the Task box should be 30px all the way around (in #617)
![Screenshot_4_10_19__11_34_AM](https://user-images.githubusercontent.com/1392130/55896802-c7f45500-5b84-11e9-90bc-37bd45a5d04c.png)
- [x] Line up the bottom of the Task module with the bottom of the subject image. (in #617) The buttons and 'need some help' should be anchored to the bottom (with 30px padding between them and the bottom of the module), additional space can be between the 'transit' button and 'need help' (in #617
![Planet_Finders_BETA___Zooniverse_-_People-powered_research](https://user-images.githubusercontent.com/1392130/55898034-61bd0180-5b87-11e9-8b57-4f9daa914ab7.png)
- [ ] When resizing the window, there's a slight lag when the data resizes to fit. Can there be an overlay with a loader to indicate that something is happening – I think this is used elsewhere in the site so if that component can be reused that would be ideal
- [x] It feels a little awkward that the background of the data is the same color as the buttons – please make it a bit darker: #003941 (better contrast for accessibility as well)
- [x] the 'tutorial' button text should be #5C5C5C while 'task' is #000 to indicate which one is selected #724
- [x] 'task' should not have a hover state, nothing happens when it's clicked #724
- [x] the tutorial doesn't scroll when it's in the tab state
![Planet_Finders_BETA___Zooniverse_-_People-powered_research](https://user-images.githubusercontent.com/1392130/55898761-e9efd680-5b88-11e9-8117-8b038e54c776.png)

### Field guide
(also in #666 but here's more)
- [x] all icons should be the same dimensions (square)
![Planet_Finders_BETA___Zooniverse_-_People-powered_research](https://user-images.githubusercontent.com/1392130/55897222-bbbcc780-5b85-11e9-9232-c1823c7da52d.png)

### Secondary modules
- [x] body copy is too small, please make all body 14px 
- [x] padding around all secondary modules should be 30px. please refer to [this document](https://invis.io/a/PM1A9Z18C9SWY2) and let me know if there's anything not addressed there.

**Comment by eatyourgreens** [comment]
>Modal text (need help, add to collections, etc) remains underlined after the modal has been closed

I think this is happening because those buttons have keyboard focus. If we remove the underline, how should focus be indicated?

**Comment by eatyourgreens** [comment]
The buttons underneath the subject are also rendering too large in Chrome, I think.
![Screenshot of the subject info buttons with the button outline shown in Chrome.](https://user-images.githubusercontent.com/59547/55944538-b83a4680-5c40-11e9-9f16-5da4d32e51de.png)

**Comment by srallen** [comment]
> I think this is happening because those buttons have keyboard focus. If we remove the underline, how should focus be indicated?

Yep. These are buttons styled to look like anchors, so use the underline text on focus and hover. You'll notice that buttons that have a change in background color on hover and focus remain focused too. If this shouldn't happen, then there's a lot of changes we'll have to make rather than rely on default browser behavior and Grommet styles.

**Comment by srallen** [comment]
> Why does 'Planet Finders BETA Tutorial' appear on each slide

The design shows a header `[Project name] Tutorial`. Should this only appear on the first slide?

**Comment by srallen** [comment]
I'm taking a look at the tutorial modal styling issues now

**Comment by srallen** [comment]
@beckyrother 

> Pagination dots are too far apart, arrows are even farther. There should be 5px between each element

Here's what this looks like: 

<img width="406" alt="Screen Shot 2019-04-11 at 2 58 33 PM" src="https://user-images.githubusercontent.com/5016731/55963203-4c6cd380-5c6a-11e9-98d6-b09f8d9cced6.png">

And this seems very small to me... too small I think for touch interaction on mobile web. The Indesign I'm seeing ~15px between each? Please let me know what you'd like here. Thanks!

**Comment by beckyrother** [comment]
Thanks @srallen and @eatyourgreens!
- To me it feels awkward that the buttons remain focused after they've been interacted with; that doesn't feel like standard web behavior. However, if it makes more sense from an accessibility standpoint, that's fine,
- [Project Name] tutorial should only appear on the first slide, or in the header on every slide, whichever is easiest
- Good point about touch targets, please switch the dots to 15px apart.

**Comment by srallen** [comment]
> The buttons underneath the subject are also rendering too large in Chrome, I think.

This might be one of the issues being caused by the class name mismatches that we're still getting in the app. I only see this issue in the app.

**Comment by srallen** [comment]
> To me it feels awkward that the buttons remain focused after they've been interacted with; that doesn't feel like standard web behavior

Right, I think the browser is still doing its default focus state management, but I think Grommet is using the focus state to add its own focus styling. I'll look to see if it is easily configurable, but if it's not we might not have this fixed before beta.

**Comment by eatyourgreens** [comment]
> To me it feels awkward that the buttons remain focused after they've been interacted with; that doesn't feel like standard web behavior. 

If I've opened the collections modal with the enter key, I think I'd expect the button to be focused again when I add the subject to a collection and close the modal. Are you thinking the keyboard focus should go somewhere else on the page?

**Comment by beckyrother** [comment]
Is there a way to only show the focus state if the keyboard is being used? It makes sense to keep the focus when using a keyboard, but that information is not as useful to a mouse user

**Comment by eatyourgreens** [comment]
>Is there a way to only show the focus state if the keyboard is being used? It makes sense to keep the focus when using a keyboard, but that information is not as useful to a mouse user

There's a proposal to add [`:focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) to CSS.

**Comment by beckyrother** [comment]
Last couple of comments:
- [ ] Add a 'get started' primary (teal solid) button on the last page of the tutorial
- [ ] Check button height, all should be 40px tall
- [ ] The task box should be the same height as the subject image, and shouldn't change height when switching to the Tutorial

**Comment by beckyrother** [comment]
Feedback modal: remove the bullet and add more details to the feedback
![image](https://user-images.githubusercontent.com/1392130/56052025-0b31fd80-5d16-11e9-8ba0-593eed9a2098.png)
Maybe the 'close' button should say 'keep classifying' or 'show me another' to give more context into why this box has come up and what will happen when they close the module.

**Comment by beckyrother** [comment]
- [ ] Add to favourites and collections buttons have hover states even though they're disabled

**Comment by srallen** [comment]
I'm going to pull out the remaining issues here into their own separate issues.
