### ISSUE TITLE
Design: survey feedback

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/front-end-monorepo#728]
Running feedback doc: 
https://docs.google.com/document/d/1fseYDk6LoBI9AiSbZRw-jz_ydnGJIv95qkob8CfBHTk/edit?usp=sharing
I'll be updating this throughout the week until the survey is closed.

--- 

### Key takeaways:
Overall very positive!! The ability to zoom is HUGE (pun intended), and this version works much better on mobile. 

---

### To update:
- [x] Dark mode (#653)
- [x] [Tooltips on toolbar](https://projects.invisionapp.com/d/main#/console/12923997/292162077/build)
- [x] Hide the tools that aren't available, people seem distressed that they're not able to use them (#732)
- [x] The subject shouldn't resize when switching between Task and Tutorial (#726)
- [ ] ~Feedback copy needs a bit of work (@mrniaboc maybe?) Check the Feedback section of the above google doc.~ Copy is set by the project team.
- [x] Field guide: keep the title and back button persistent at the top of the screen so it's easy to navigate back to the main list (#783)

**Comment by eatyourgreens** [comment]
Something I'm getting from the comments about feedback is that it would be more useful if we showed those transits in the subject viewer, rather than in a popup.

The randomly placed feedback is confusing people too, since it doesn't correlate with any actual transits in the test data.

**Comment by eatyourgreens** [comment]
People are finding zooming quite cumbersome, and miss the keyboard controls to zoom while drawing (#722.)

**Comment by beckyrother** [comment]
People seem to like the scroll to zoom but are frustrated when the window scrolls after the image has been zoomed to the max

**Comment by srallen** [comment]
Yeah in retrospect we should've used real data. After reading the feedback form comments, that really tripped some people up despite the email in bold telling them it was fake.

**Comment by srallen** [comment]
The tooltips were basically done in #355 but a grommet bug was holding it back. It's possible that bug is no longer an issue. I closed it because the branch got far behind master. I think what I did in #355 could be broken up into a few smaller PRs.

**Comment by srallen** [comment]
> Field guide: keep the title and back button persistent at the top of the screen so it's easy to navigate back to the main list

@beckyrother When you have a moment, could you show me what this means (or post screenshots if that's easier)? It seems to me it's staying at the top? Thanks!

**Comment by beckyrother** [comment]
@srallen Yes, the navigation should stay at the top. I'll post a screenshot asap

**Comment by rogerhutchings** [comment]
ping @beckyrother for screenshot

**Comment by srallen** [comment]
@rogerhutchings she showed me in person instead the other day.
